-- Employee count by designation
SELECT DESIGNATION, COUNT(E_ID) AS EMP_COUNT
FROM EMPLOYEE
GROUP BY DESIGNATION
ORDER BY EMP_COUNT DESC;

-- Employees in NY branch
SELECT E_NAME, DESIGNATION
FROM EMPLOYEE
WHERE E_BRANCH = 'NY';
